apiVersion: v1
kind: Pod
metadata:
  name: stat-website
  labels:
    app: web1
spec:
  containers:
    - name: stat-wbsite-cont
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: web-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: web-vol
      hostPath:
        path: /adhamk8s
        type: Directory
